name: Build Windows Form

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-dotnet-app1:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: app_WindowsForm/WindowsFormsAppFieldIntersectionPoint
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
  
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore NuGet packages
      run: nuget restore WindowsFormsApp1/WindowsFormsApp1.sln

    - name: Use NuGet to install .NET Framework 4.8
      run: nuget install Microsoft.Net.Compilers -Version 3.8.0

    - name: Build app for release
      run: msbuild WindowsFormsApp1/WindowsFormsApp1.sln

      
#   build-dotnet-app2:
#     runs-on: [windows-latest]
#     defaults:
#       run:
#         working-directory: app_WindowsForm/WindowsFormsAppLab7_2
#     steps:
#     - uses: actions/checkout@v4
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v4
#       with:
#         dotnet-version: 8.0.x
#     - name: Restore dependencies
#       run: dotnet restore
#     - name: Build
#       run: dotnet build --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal